name: publish-to-github-pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      NEXT_PUBLIC_WEB3FORMS_ENDPOINT: ${{ secrets.NEXT_PUBLIC_WEB3FORMS_ENDPOINT || vars.NEXT_PUBLIC_WEB3FORMS_ENDPOINT }}
      NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY: ${{ secrets.NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY || vars.NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY }}
      NEXT_PUBLIC_WEB3FORMS_HCAPTCHA_SITEKEY: ${{ secrets.NEXT_PUBLIC_WEB3FORMS_HCAPTCHA_SITEKEY || vars.NEXT_PUBLIC_WEB3FORMS_HCAPTCHA_SITEKEY }}
      NEXT_PUBLIC_WEB3FORMS_ENABLE_HCAPTCHA: ${{ secrets.NEXT_PUBLIC_WEB3FORMS_ENABLE_HCAPTCHA || vars.NEXT_PUBLIC_WEB3FORMS_ENABLE_HCAPTCHA || 'false' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify required env
        run: |
          REQUIRED_VARS=(NEXT_PUBLIC_WEB3FORMS_ENDPOINT NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY)
          OPTIONAL_VARS=(NEXT_PUBLIC_WEB3FORMS_HCAPTCHA_SITEKEY)

          for var in "${REQUIRED_VARS[@]}"; do
            if [ -z "${!var:-}" ]; then
              echo "::error title=Missing environment variable::${var} must be provided via repository secrets or variables."
              exit 1
            fi
          done

          if [ "${NEXT_PUBLIC_WEB3FORMS_ENABLE_HCAPTCHA,,}" = "true" ] && [ -z "${NEXT_PUBLIC_WEB3FORMS_HCAPTCHA_SITEKEY:-}" ]; then
            echo "::error title=Missing hCaptcha sitekey::NEXT_PUBLIC_WEB3FORMS_ENABLE_HCAPTCHA is true but NEXT_PUBLIC_WEB3FORMS_HCAPTCHA_SITEKEY is unset."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build with Next.js
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
